from wordcloud import  WordCloud,STOPWORDS
from matplotlib import  pyplot as plt

file  = open("detail_txt.txt", "r").read()
stopwords = set(STOPWORDS)
stopwords.add("任职")
stopwords.add("要求")
stopwords.add("关键")
stopwords.add("关键字")
stopwords.add("数据仓库")
stopwords.add("仓库")
stopwords.add("工程")
stopwords.add("工程师")
stopwords.add("计算")
stopwords.add("计算机")
stopwords.add("算机")
stopwords.add("负责")
stopwords.add("产品")
stopwords.add("职能")
stopwords.add("类别")
stopwords.add("以上")
stopwords.add("上学")
stopwords.add("以上学历")
stopwords.add("学历")
stopwords.add("工作")
stopwords.add("技术")
stopwords.add("进行")
stopwords.add("项目")
stopwords.add("目的")
stopwords.add("优先")
stopwords.add("先考")
stopwords.add("考虑")
stopwords.add("技术移民")
stopwords.add("解决")
stopwords.add("解决方案")
stopwords.add("u0026nbsp")
stopwords.add("u0026")
stopwords.add("p3")
stopwords.add("p4")
stopwords.add("p1")
stopwords.add("p2")
stopwords.add("p5")
stopwords.add("p6")
stopwords.add("相关")
stopwords.add("相关专业")
stopwords.add("专业")
stopwords.add("经验")
stopwords.add("软件工程")
stopwords.add("软件")
stopwords.add("弹性")
stopwords.add("薪水")
stopwords.add("不含")
stopwords.add("项目管理")
stopwords.add("责任心")
stopwords.add("管理员")
stopwords.add("熟悉")
stopwords.add("移民")
stopwords.add("业务")
stopwords.add("需求")
stopwords.add("月薪")
stopwords.add("新币")
stopwords.add("本科")
stopwords.add("以及")
stopwords.add("BI")
stopwords.add("系统")
stopwords.add("具备")
stopwords.add("管理")
stopwords.add("良好")
stopwords.add("技术支持")
stopwords.add("表达能力")



stopwords.add("数据")
stopwords.add("沟通")
stopwords.add("能力")
stopwords.add("团队")
stopwords.add("合作")
stopwords.add("数据库")
stopwords.add("据库")
stopwords.add("数据分析")
stopwords.add("分析")
stopwords.add("设计")
stopwords.add("开发")
stopwords.add("架构设计")
stopwords.add("可视化")
stopwords.add("SQLServer")
stopwords.add("报表")
stopwords.add("数据模型")
stopwords.add("大数据")
stopwords.add("平台")
stopwords.add("运营")


stopwords.add("互联")
stopwords.add("互联网")
stopwords.add("联网")
stopwords.add("熟练")
stopwords.add("使用")
stopwords.add("熟练掌握")
stopwords.add("数据挖掘")
wordcloud = WordCloud(background_color = "white", width = 1000, height = 800,stopwords=stopwords,
                      margin= 2, font_path= '‪C:\Windows\Fonts\SIMLI.TTF').generate(file)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()
wordcloud.to_file('detail.png')
print("success")
